/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginforminmysql;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author OEM
 */
public class admin extends javax.swing.JFrame {

     Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs=null;
             Connection con1 = null;
    PreparedStatement pat1 = null;
    ResultSet rs1=null;
     Connection con2 = null;
    PreparedStatement pat2 = null;
    ResultSet rs2=null;
    public admin() {
        initComponents();
        showTable();
        showTableSanatci();
        showTableAlbum();
        showTableSarki();
         showTableAdmin(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sekme = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sanatcikaydet = new javax.swing.JButton();
        SAid = new javax.swing.JTextField();
        SAname = new javax.swing.JTextField();
        SAulke = new javax.swing.JTextField();
        sanatcisil = new javax.swing.JButton();
        sanatciguncelle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtAid = new javax.swing.JTextField();
        txtAalbumadi = new javax.swing.JTextField();
        txtAsanatciadi = new javax.swing.JTextField();
        txtAsarkiadi = new javax.swing.JTextField();
        txtAtarih = new javax.swing.JTextField();
        albumkaydet = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        albumguncelle = new javax.swing.JButton();
        albumsil = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        albumtablo = new javax.swing.JTable();
        txtalbumbaglantiid = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sarkikaydet = new javax.swing.JButton();
        txtSid = new javax.swing.JTextField();
        txtSname = new javax.swing.JTextField();
        txtStarih = new javax.swing.JTextField();
        txtSdinlenmesayisi = new javax.swing.JTextField();
        txtSsanatcialbum = new javax.swing.JTextField();
        txtStur = new javax.swing.JTextField();
        txtSsure = new javax.swing.JTextField();
        sarkisil = new javax.swing.JButton();
        sarkiguncelle = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        sarkitablo = new javax.swing.JTable();
        txtsarkibaglanti = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtıd = new javax.swing.JTextField();
        txtulke = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtsifre = new javax.swing.JTextField();
        cmb = new javax.swing.JComboBox<>();
        kullanicikaydet = new javax.swing.JButton();
        kullaniciguncelle = new javax.swing.JButton();
        kullanicisil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kullanici = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        admincmb = new javax.swing.JComboBox<>();
        txtadminad = new javax.swing.JTextField();
        txtadminsifre = new javax.swing.JTextField();
        adminkaydet = new javax.swing.JButton();
        adminsil = new javax.swing.JButton();
        adminguncelle = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        admintablo = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        txtadminID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cikisbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setText("ID");

        jLabel20.setText("Adı");

        jLabel21.setText("Ülke");

        sanatcikaydet.setText("KAYDET");
        sanatcikaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatcikaydetActionPerformed(evt);
            }
        });

        SAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAidActionPerformed(evt);
            }
        });

        sanatcisil.setText("SİL");
        sanatcisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatcisilActionPerformed(evt);
            }
        });

        sanatciguncelle.setText("GÜNCELLE");
        sanatciguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciguncelleActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SAid, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SAname, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SAulke, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel21)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sanatcikaydet)
                        .addGap(51, 51, 51)
                        .addComponent(sanatcisil)
                        .addGap(75, 75, 75)
                        .addComponent(sanatciguncelle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(SAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(jLabel20))
                            .addComponent(SAname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SAulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(156, 156, 156)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sanatcikaydet)
                            .addComponent(sanatcisil)
                            .addComponent(sanatciguncelle)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        sekme.addTab("SANATÇI KAYDET", jPanel4);

        albumkaydet.setText("Kaydet");
        albumkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumkaydetActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        jLabel15.setText("Albüm Adı");

        jLabel16.setText("Sanatçı Adı");

        jLabel17.setText("Şarkı Adı");

        jLabel18.setText("Tarih");

        albumguncelle.setText("Güncelle");
        albumguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumguncelleActionPerformed(evt);
            }
        });

        albumsil.setText("Sil");
        albumsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumsilActionPerformed(evt);
            }
        });

        albumtablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(albumtablo);

        txtalbumbaglantiid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalbumbaglantiidActionPerformed(evt);
            }
        });

        jLabel25.setText("Sanatçı adı sanatçı kaydet sekmesinden güncellenmektedir");

        jLabel27.setText("Bağlantı ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel27))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAtarih, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtAsarkiadi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtAalbumadi)
                                        .addComponent(txtAid)
                                        .addComponent(txtAsanatciadi, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addComponent(txtalbumbaglantiid)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(albumkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(albumsil, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(albumguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAalbumadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsanatciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtAsarkiadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtAtarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtalbumbaglantiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumkaydet)
                    .addComponent(albumsil)
                    .addComponent(albumguncelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        sekme.addTab("ALBÜM ", jPanel3);

        jLabel2.setText("ID");

        jLabel8.setText("Şarkı Adı");

        jLabel9.setText("Tarih");

        jLabel10.setText("Sanatçı Albümü");

        jLabel11.setText("Tür");

        jLabel12.setText("Süre");

        jLabel13.setText("Dinlenme Sayısı");

        sarkikaydet.setText("Kaydet");
        sarkikaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkikaydetActionPerformed(evt);
            }
        });

        sarkisil.setText("Sil");
        sarkisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkisilActionPerformed(evt);
            }
        });

        sarkiguncelle.setText("Güncelle");
        sarkiguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarkiguncelleActionPerformed(evt);
            }
        });

        sarkitablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(sarkitablo);

        jLabel26.setText("Bağlantı ıd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(sarkikaydet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsarkibaglanti, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSid)
                                    .addComponent(txtSname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSsure, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStur)
                                    .addComponent(txtStarih, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSsanatcialbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtSdinlenmesayisi))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(sarkisil)
                        .addGap(126, 126, 126)
                        .addComponent(sarkiguncelle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtSdinlenmesayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtStarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSsanatcialbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtStur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtSsure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtsarkibaglanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sarkikaydet)
                    .addComponent(sarkisil)
                    .addComponent(sarkiguncelle))
                .addGap(62, 62, 62))
        );

        sekme.addTab("ŞARKI ", jPanel1);

        jLabel1.setText("Ad Soyad");

        jLabel3.setText("ID");

        jLabel6.setText("Ülke");

        jLabel4.setText("Email");

        jLabel7.setText("Abonelik Türü");

        jLabel5.setText("Şifre");

        txtsifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsifreActionPerformed(evt);
            }
        });

        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premium", "Normal" }));

        kullanicikaydet.setText("Kaydet");
        kullanicikaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicikaydetActionPerformed(evt);
            }
        });

        kullaniciguncelle.setText("Güncelle");
        kullaniciguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciguncelleActionPerformed(evt);
            }
        });

        kullanicisil.setText("Sil");
        kullanicisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicisilActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kullanici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtulke)
                                .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(txtıd))
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kullanicikaydet)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullanici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kullanicisil, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(kullaniciguncelle)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtıd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullanicikaydet)
                            .addComponent(kullanicisil)
                            .addComponent(kullaniciguncelle)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(kullanici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        sekme.addTab("KULLANICI ", jPanel2);

        jLabel22.setText("Admin Adı");

        jLabel23.setText("Şifre");

        admincmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin" }));

        adminkaydet.setText("Kaydet");
        adminkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminkaydetActionPerformed(evt);
            }
        });

        adminsil.setText("Sil");
        adminsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsilActionPerformed(evt);
            }
        });

        adminguncelle.setText("Güncelle");
        adminguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminguncelleActionPerformed(evt);
            }
        });

        admintablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(admintablo);

        jLabel24.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(adminkaydet)
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(admincmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(adminsil)
                                .addGap(59, 59, 59)
                                .addComponent(adminguncelle))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtadminsifre)
                            .addComponent(txtadminad)
                            .addComponent(txtadminID, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(txtadminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtadminad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtadminsifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(admincmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminkaydet)
                    .addComponent(adminsil)
                    .addComponent(adminguncelle))
                .addGap(227, 227, 227))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sekme.addTab("ADMİN", jPanel5);

        cikisbuton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        cikisbuton.setText("ÇIKIŞ");
        cikisbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(cikisbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(cikisbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        sekme.addTab("ÇIKIŞ", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sekme, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(sekme, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void albumkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumkaydetActionPerformed
       
        
         try
        { String sql5 = "INSERT INTO `album`( Aalbumadi,Asanatciadi,Asarkiadi,Atarih,albumbaglanti_id) VALUES (?,?,?,?,?)";

              con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql5);
          //   pat.setString(1,txtAid.getText());
             pat.setString(1,txtAalbumadi.getText());
             pat.setString(2,txtAsanatciadi.getText());
           pat.setString(3,txtAsarkiadi.getText());
            pat.setString(4,txtAtarih.getText());
           pat.setString(5,txtalbumbaglantiid.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Kayıt Başarılı");
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
         showTableAlbum();
    }//GEN-LAST:event_albumkaydetActionPerformed

    private void sanatcikaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatcikaydetActionPerformed
   try
        { String sql1 ="INSERT INTO `sanatcii`( SAad, SAulke) VALUES (?,?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql1);
        //    pat.setString(1,SAıd.getText());
            pat.setString(1,SAname.getText());
            pat.setString(2,SAulke.getText());
           
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Kayıt Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableSanatci();  
   
   
    }//GEN-LAST:event_sanatcikaydetActionPerformed

    private void sarkikaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkikaydetActionPerformed
         try
        { String sql =  "INSERT INTO `sarki`( `Sad`, `Starih`, `Ssantcialbum`, `Stur`, `Ssure`, `Sdinlenmesayisi`,sarkibaglanti_id) VALUES (?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
           // pat.setString(1,txtSid.getText());
            pat.setString(1,txtSname.getText());
            pat.setString(2,txtStarih.getText());
            pat.setString(3,txtSsanatcialbum.getText());
            pat.setString(4,txtStur.getText());
            pat.setString(5,txtSsure.getText());
            pat.setString(6,txtSdinlenmesayisi.getText());
             pat.setString(7,txtsarkibaglanti.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Kayıt Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
         showTableSarki();
    }//GEN-LAST:event_sarkikaydetActionPerformed

    private void kullanicisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicisilActionPerformed

        try
        { String sql ="DELETE FROM `kullanici` WHERE ID=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);

            pat.setString(1,txtıd.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTable(); 
    }//GEN-LAST:event_kullanicisilActionPerformed

    private void kullanicikaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicikaydetActionPerformed
 
        try
        { String sql ="INSERT INTO `kullanici`(`ad`, `ID`, `email`, `sifre`, `ulke`, `abonelikbilgisi`,usertype) VALUES (?,?,?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtname.getText());
            pat.setString(2,txtıd.getText());
            pat.setString(3,txtemail.getText());
            pat.setString(4,txtsifre.getText());
            pat.setString(5,txtulke.getText());
            pat.setString(6,String.valueOf(cmb.getSelectedItem()));
            pat.setString(7,String.valueOf(kullanici.getSelectedItem()));
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Kayıt Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTable(); 
    }//GEN-LAST:event_kullanicikaydetActionPerformed
public void showTable(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot"); 
        String sql="SELECT * FROM `kullanici`";
        pat=con.prepareCall(sql);
        rs=pat.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, e);
    }
}
public void showTableSanatci(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot"); 
        String sql="SELECT * FROM `sanatcii`";
        pat=con.prepareCall(sql);
        rs=pat.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, e);
    }
}
public void showTableAlbum(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot"); 
        String sql="SELECT * FROM `album`";
        pat=con.prepareCall(sql);
        rs=pat.executeQuery();
        albumtablo.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, e);
    }
}
public void showTableSarki(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot"); 
        String sql="SELECT * FROM `sarki`";
        pat=con.prepareCall(sql);
        rs=pat.executeQuery();
        sarkitablo.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, e);
    }}
public void showTableAdmin(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot"); 
        String sql="SELECT * FROM `admin`";
        pat=con.prepareCall(sql);
        rs=pat.executeQuery();
        admintablo.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, e);
    
}
}
    private void txtsifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsifreActionPerformed

    private void kullaniciguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciguncelleActionPerformed
       try
        { String sql ="UPDATE `kullanici` SET `ad`=?,`email`=?,`sifre`=?,`ulke`=?,`abonelikbilgisi`=? WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtname.getText());
            pat.setString(6,txtıd.getText());
            pat.setString(2,txtemail.getText());
            pat.setString(3,txtsifre.getText());
            pat.setString(4,txtulke.getText());
            pat.setString(5,String.valueOf(cmb.getSelectedItem()));
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTable(); 
    }//GEN-LAST:event_kullaniciguncelleActionPerformed
//////////////////////////////////////////////////////////////////////
    private void sanatcisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatcisilActionPerformed
        try
        { String sql ="DELETE FROM `sanatcii` WHERE SAID=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);

            pat.setString(1,SAid.getText());

            pat.executeUpdate();
          //  JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

            String sql3 ="DELETE FROM `album` WHERE albumbaglanti_id=?";

            con1 = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat1 = con1.prepareStatement(sql3);

            pat1.setString(1,SAid.getText());

             pat1.executeUpdate();
           // JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");
            String sql2 ="DELETE FROM `sarki` WHERE albumbaglanti_id=?";

         //   con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat2 = con2.prepareStatement(sql2);

            pat2.setString(1,SAid.getText());

            pat2.executeUpdate();
            JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableSanatci(); 
 showTableSarki();
 showTableAlbum();
    }//GEN-LAST:event_sanatcisilActionPerformed
//****************************************************************************
    private void sanatciguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciguncelleActionPerformed
         try
        { String sql = "UPDATE `sanatcii` SET `SAad`=?,`SAulke`=? WHERE `SAID`=?";
       
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,SAname.getText());
            pat.setString(3,SAid.getText());
            pat.setString(2,SAulke.getText());
           
            pat.executeUpdate();
   //         JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");
String sql2 = " UPDATE album SET Asanatciadi=? WHERE  albumbaglanti_id=?";
   // " UPDATE album SET Aalbumadi=?,Asarkiadi=?,Atarih=? WHERE  AID=?";
            con2 = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat2 = con2.prepareStatement(sql2);
          pat2.setString(1,SAname.getText());
            pat2.setString(2,SAid.getText());
            pat2.executeUpdate();
      //      JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");
                                      /*  String sql1= " UPDATE sarki SET Sad=? WHERE  sarkibaglanti_id=?";
    
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat1 = con1.prepareStatement(sql1);
           pat1.setString(1,SAname.getText());
            pat1.setString(2,SAid.getText());
            pat1.executeUpdate();      */
     //       JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableSanatci(); 
 showTableAlbum();
 showTableSarki();
    }//GEN-LAST:event_sanatciguncelleActionPerformed

    private void albumsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumsilActionPerformed
      
         try
        { String sql3 ="DELETE FROM `album` WHERE AID=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql3);

            pat.setString(1,txtAid.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableAlbum(); 
             
        
        
    }//GEN-LAST:event_albumsilActionPerformed

    private void albumguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumguncelleActionPerformed
      
       
      /*   try { String sql = " UPDATE album SET Aalbumadi=?,Asarkiadi=?,Atarih=? WHERE  AID=?";
    
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtAalbumadi.getText());
        //    pat.setString(2,txtAsanatciadi.getText());
            pat.setString(2,txtAsarkiadi.getText());
            pat.setString(3,txtAtarih.getText());
            pat.setString(4,txtAid.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");

        }*/
             try
        { String sql = " UPDATE album SET Aalbumadi=?,Asanatciadi=?,Asarkiadi=?,Atarih=? WHERE  AID=?";
    
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtAalbumadi.getText());
            pat.setString(2,txtAsanatciadi.getText());
            pat.setString(3,txtAsarkiadi.getText());
            pat.setString(4,txtAtarih.getText());
            pat.setString(5,txtAid.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");
String sql1 = "UPDATE `sanatcii` SET `SAad`=? WHERE `SAID`=?";
       
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat1 = con1.prepareStatement(sql1);
            pat1.setString(1,txtAsanatciadi.getText());
          
            pat1.setString(2,txtalbumbaglantiid.getText());
           
            pat1.executeUpdate();
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableAlbum();  
        showTableSanatci();
        showTableSarki();
        
        
        
        
    }//GEN-LAST:event_albumguncelleActionPerformed

    private void sarkisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkisilActionPerformed
      
        
          try
        { String sql ="DELETE FROM `sarki` WHERE SID=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);

            pat.setString(1,txtSid.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableSarki();
                 
        
        
        
    }//GEN-LAST:event_sarkisilActionPerformed

    private void sarkiguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarkiguncelleActionPerformed
     
     try
        { String sql = " UPDATE sarki SET Sad=?,Starih=?,Ssantcialbum=?,Stur=?,Ssure=?,Sdinlenmesayisi=? WHERE  SID=?";
    
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(6,txtSdinlenmesayisi.getText());
            pat.setString(1,txtSname.getText());
              pat.setString(2,txtStarih.getText());
            pat.setString(3,txtSsanatcialbum.getText());
            pat.setString(5,txtSsure.getText());
          
            pat.setString(4,txtStur.getText());
            pat.setString(7,txtSid.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableSarki();      
        
        
        
        
    }//GEN-LAST:event_sarkiguncelleActionPerformed

    private void adminkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminkaydetActionPerformed
      
         try
        { String sql ="INSERT INTO `admin`(`adminID`, `adminad`, `adminsifre`, `admintype`) VALUES (?,?,?,?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtadminID.getText());
            pat.setString(2,txtadminad.getText());
            pat.setString(3,txtadminsifre.getText());
            
          
            pat.setString(4,String.valueOf(admincmb.getSelectedItem()));
           
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Kayıt Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableAdmin(); 
        
        
        
        
    }//GEN-LAST:event_adminkaydetActionPerformed

    private void adminsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsilActionPerformed
      
          try
        { String sql ="DELETE FROM `admin` WHERE adminID=?";

            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);

            pat.setString(1,txtadminID.getText());

            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Silme İşlemi Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableAdmin();
        
        
        
        
        
        
    }//GEN-LAST:event_adminsilActionPerformed

    private void adminguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminguncelleActionPerformed
     
         try
        { String sql = " UPDATE admin SET adminad=?,adminsifre=?,admintype=? WHERE  adminID=?";
    
            con = DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin","root","rootroot");
            pat = con.prepareStatement(sql);
            pat.setString(1,txtadminad.getText());
            pat.setString(2,txtadminsifre.getText());
             pat.setString(3,String.valueOf(admincmb.getSelectedItem()));
            pat.setString(4,txtadminID.getText());
            pat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Güncelleme Başarılı");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
 showTableAdmin();   
        
        
        
        
        
    }//GEN-LAST:event_adminguncelleActionPerformed

    private void cikisbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisbutonActionPerformed
       
        NewJFrame frame =new NewJFrame();
         
               frame.setVisible(true);
               this.setVisible(false); 
        
        
        
    }//GEN-LAST:event_cikisbutonActionPerformed

    private void txtalbumbaglantiidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalbumbaglantiidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalbumbaglantiidActionPerformed

    private void SAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SAid;
    private javax.swing.JTextField SAname;
    private javax.swing.JTextField SAulke;
    private javax.swing.JComboBox<String> admincmb;
    private javax.swing.JButton adminguncelle;
    private javax.swing.JButton adminkaydet;
    private javax.swing.JButton adminsil;
    private javax.swing.JTable admintablo;
    private javax.swing.JButton albumguncelle;
    private javax.swing.JButton albumkaydet;
    private javax.swing.JButton albumsil;
    private javax.swing.JTable albumtablo;
    private javax.swing.JButton cikisbuton;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> kullanici;
    private javax.swing.JButton kullaniciguncelle;
    private javax.swing.JButton kullanicikaydet;
    private javax.swing.JButton kullanicisil;
    private javax.swing.JButton sanatciguncelle;
    private javax.swing.JButton sanatcikaydet;
    private javax.swing.JButton sanatcisil;
    private javax.swing.JButton sarkiguncelle;
    private javax.swing.JButton sarkikaydet;
    private javax.swing.JButton sarkisil;
    private javax.swing.JTable sarkitablo;
    private javax.swing.JTabbedPane sekme;
    private javax.swing.JTextField txtAalbumadi;
    private javax.swing.JTextField txtAid;
    private javax.swing.JTextField txtAsanatciadi;
    private javax.swing.JTextField txtAsarkiadi;
    private javax.swing.JTextField txtAtarih;
    private javax.swing.JTextField txtSdinlenmesayisi;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtSsanatcialbum;
    private javax.swing.JTextField txtSsure;
    private javax.swing.JTextField txtStarih;
    private javax.swing.JTextField txtStur;
    private javax.swing.JTextField txtadminID;
    private javax.swing.JTextField txtadminad;
    private javax.swing.JTextField txtadminsifre;
    private javax.swing.JTextField txtalbumbaglantiid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsarkibaglanti;
    private javax.swing.JTextField txtsifre;
    private javax.swing.JTextField txtulke;
    private javax.swing.JTextField txtıd;
    // End of variables declaration//GEN-END:variables
}
